<?php
    
namespace Prehmis\HL7Bundle\Tables\v26;

use Elao\Enum\ChoiceEnumTrait;
use Elao\Enum\ReadableEnum;

/**
 * Description of T0399
 * Country Code
 * HL7 version 2.6
 *
 */
final class T0399 extends ReadableEnum
{
    use ChoiceEnumTrait;

    const ABW = 'ABW';
    const AFG = 'AFG';
    const AGO = 'AGO';
    const AIA = 'AIA';
    const ALA = 'ALA';
    const ALB = 'ALB';
    const AND = 'AND';
    const ARE = 'ARE';
    const ARG = 'ARG';
    const ARM = 'ARM';
    const ASM = 'ASM';
    const ATA = 'ATA';
    const ATF = 'ATF';
    const ATG = 'ATG';
    const AUS = 'AUS';
    const AUT = 'AUT';
    const AZE = 'AZE';
    const BDI = 'BDI';
    const BEL = 'BEL';
    const BEN = 'BEN';
    const BES = 'BES';
    const BFA = 'BFA';
    const BGD = 'BGD';
    const BGR = 'BGR';
    const BHR = 'BHR';
    const BHS = 'BHS';
    const BIH = 'BIH';
    const BLM = 'BLM';
    const BLR = 'BLR';
    const BLZ = 'BLZ';
    const BMU = 'BMU';
    const BOL = 'BOL';
    const BRA = 'BRA';
    const BRB = 'BRB';
    const BRN = 'BRN';
    const BTN = 'BTN';
    const BVT = 'BVT';
    const BWA = 'BWA';
    const CAF = 'CAF';
    const CAN = 'CAN';
    const CCK = 'CCK';
    const CHE = 'CHE';
    const CHL = 'CHL';
    const CHN = 'CHN';
    const CIV = 'CIV';
    const CMR = 'CMR';
    const COD = 'COD';
    const COG = 'COG';
    const COK = 'COK';
    const COL = 'COL';
    const COM = 'COM';
    const CPV = 'CPV';
    const CRI = 'CRI';
    const CUB = 'CUB';
    const CUW = 'CUW';
    const CXR = 'CXR';
    const CYM = 'CYM';
    const CYP = 'CYP';
    const CZE = 'CZE';
    const DEU = 'DEU';
    const DJI = 'DJI';
    const DMA = 'DMA';
    const DNK = 'DNK';
    const DOM = 'DOM';
    const DZA = 'DZA';
    const ECU = 'ECU';
    const EGY = 'EGY';
    const ERI = 'ERI';
    const ESH = 'ESH';
    const ESP = 'ESP';
    const EST = 'EST';
    const ETH = 'ETH';
    const FIN = 'FIN';
    const FJI = 'FJI';
    const FLK = 'FLK';
    const FRA = 'FRA';
    const FRO = 'FRO';
    const FSM = 'FSM';
    const GAB = 'GAB';
    const GBR = 'GBR';
    const GEO = 'GEO';
    const GGY = 'GGY';
    const GHA = 'GHA';
    const GIB = 'GIB';
    const GIN = 'GIN';
    const GLP = 'GLP';
    const GMB = 'GMB';
    const GNB = 'GNB';
    const GNQ = 'GNQ';
    const GRC = 'GRC';
    const GRD = 'GRD';
    const GRL = 'GRL';
    const GTM = 'GTM';
    const GUF = 'GUF';
    const GUM = 'GUM';
    const GUY = 'GUY';
    const HKG = 'HKG';
    const HMD = 'HMD';
    const HND = 'HND';
    const HRV = 'HRV';
    const HTI = 'HTI';
    const HUN = 'HUN';
    const IDN = 'IDN';
    const IMN = 'IMN';
    const IND = 'IND';
    const IOT = 'IOT';
    const IRL = 'IRL';
    const IRN = 'IRN';
    const IRQ = 'IRQ';
    const ISL = 'ISL';
    const ISR = 'ISR';
    const ITA = 'ITA';
    const JAM = 'JAM';
    const JEY = 'JEY';
    const JOR = 'JOR';
    const JPN = 'JPN';
    const KAZ = 'KAZ';
    const KEN = 'KEN';
    const KGZ = 'KGZ';
    const KHM = 'KHM';
    const KIR = 'KIR';
    const KNA = 'KNA';
    const KOR = 'KOR';
    const KWT = 'KWT';
    const LAO = 'LAO';
    const LBN = 'LBN';
    const LBR = 'LBR';
    const LBY = 'LBY';
    const LCA = 'LCA';
    const LIE = 'LIE';
    const LKA = 'LKA';
    const LSO = 'LSO';
    const LTU = 'LTU';
    const LUX = 'LUX';
    const LVA = 'LVA';
    const MAC = 'MAC';
    const MAF = 'MAF';
    const MAR = 'MAR';
    const MCO = 'MCO';
    const MDA = 'MDA';
    const MDG = 'MDG';
    const MDV = 'MDV';
    const MEX = 'MEX';
    const MHL = 'MHL';
    const MKD = 'MKD';
    const MLI = 'MLI';
    const MLT = 'MLT';
    const MMR = 'MMR';
    const MNE = 'MNE';
    const MNG = 'MNG';
    const MNP = 'MNP';
    const MOZ = 'MOZ';
    const MRT = 'MRT';
    const MSR = 'MSR';
    const MTQ = 'MTQ';
    const MUS = 'MUS';
    const MWI = 'MWI';
    const MYS = 'MYS';
    const MYT = 'MYT';
    const NAM = 'NAM';
    const NCL = 'NCL';
    const NER = 'NER';
    const NFK = 'NFK';
    const NGA = 'NGA';
    const NIC = 'NIC';
    const NIU = 'NIU';
    const NLD = 'NLD';
    const NOR = 'NOR';
    const NPL = 'NPL';
    const NRU = 'NRU';
    const NZL = 'NZL';
    const OMN = 'OMN';
    const PAK = 'PAK';
    const PAN = 'PAN';
    const PCN = 'PCN';
    const PER = 'PER';
    const PHL = 'PHL';
    const PLW = 'PLW';
    const PNG = 'PNG';
    const POL = 'POL';
    const PRI = 'PRI';
    const PRK = 'PRK';
    const PRT = 'PRT';
    const PRY = 'PRY';
    const PSE = 'PSE';
    const PYF = 'PYF';
    const QAT = 'QAT';
    const REU = 'REU';
    const ROU = 'ROU';
    const RUS = 'RUS';
    const RWA = 'RWA';
    const SAU = 'SAU';
    const SDN = 'SDN';
    const SEN = 'SEN';
    const SGP = 'SGP';
    const SGS = 'SGS';
    const SHN = 'SHN';
    const SJM = 'SJM';
    const SLB = 'SLB';
    const SLE = 'SLE';
    const SLV = 'SLV';
    const SMR = 'SMR';
    const SOM = 'SOM';
    const SPM = 'SPM';
    const SRB = 'SRB';
    const STP = 'STP';
    const SUR = 'SUR';
    const SVK = 'SVK';
    const SVN = 'SVN';
    const SWE = 'SWE';
    const SWZ = 'SWZ';
    const SXM = 'SXM';
    const SYC = 'SYC';
    const SYR = 'SYR';
    const TCA = 'TCA';
    const TCD = 'TCD';
    const TGO = 'TGO';
    const THA = 'THA';
    const TJK = 'TJK';
    const TKL = 'TKL';
    const TKM = 'TKM';
    const TLS = 'TLS';
    const TON = 'TON';
    const TTO = 'TTO';
    const TUN = 'TUN';
    const TUR = 'TUR';
    const TUV = 'TUV';
    const TWN = 'TWN';
    const TZA = 'TZA';
    const UGA = 'UGA';
    const UKR = 'UKR';
    const UMI = 'UMI';
    const URY = 'URY';
    const USA = 'USA';
    const UZB = 'UZB';
    const VAT = 'VAT';
    const VCT = 'VCT';
    const VEN = 'VEN';
    const VGB = 'VGB';
    const VIR = 'VIR';
    const VNM = 'VNM';
    const VUT = 'VUT';
    const WLF = 'WLF';
    const WSM = 'WSM';
    const YEM = 'YEM';
    const ZAF = 'ZAF';
    const ZMB = 'ZMB';
    const ZWE = 'ZWE';
            
    public static function choices(): array
    {
        return [
            self::ABW => 'Aruba',
            self::AFG => 'Afghanistan',
            self::AGO => 'Angola',
            self::AIA => 'Anguilla',
            self::ALA => 'Aland Islands',
            self::ALB => 'Albania',
            self::AND => 'Andorra',
            self::ARE => 'United Arab Emirates',
            self::ARG => 'Argentina',
            self::ARM => 'Armenia',
            self::ASM => 'American Samoa',
            self::ATA => 'Antarctica',
            self::ATF => 'French Southern Territories',
            self::ATG => 'Antigua and Barbuda',
            self::AUS => 'Australia',
            self::AUT => 'Austria',
            self::AZE => 'Azerbaijan',
            self::BDI => 'Burundi',
            self::BEL => 'Belgium',
            self::BEN => 'Benin',
            self::BES => 'Bonaire, Saint Eustatius and Saba',
            self::BFA => 'Burkina Faso',
            self::BGD => 'Bangladesh',
            self::BGR => 'Bulgaria',
            self::BHR => 'Bahrain',
            self::BHS => 'Bahamas',
            self::BIH => 'Bosnia and Herzegovina',
            self::BLM => 'Saint Barthélemy',
            self::BLR => 'Belarus',
            self::BLZ => 'Belize',
            self::BMU => 'Bermuda',
            self::BOL => 'Bolivia, Plurinational State of',
            self::BRA => 'Brazil',
            self::BRB => 'Barbados',
            self::BRN => 'Brunei Darussalam',
            self::BTN => 'Bhutan',
            self::BVT => 'Bouvet Island',
            self::BWA => 'Botswana',
            self::CAF => 'Central African Republic',
            self::CAN => 'Canada',
            self::CCK => 'Cocos (Keeling) Islands',
            self::CHE => 'Switzerland',
            self::CHL => 'Chile',
            self::CHN => 'China',
            self::CIV => 'Cote d Ivoire',
            self::CMR => 'Cameroon',
            self::COD => 'Congo, the Democratic Republic of the',
            self::COG => 'Congo',
            self::COK => 'Cook Islands',
            self::COL => 'Colombia',
            self::COM => 'Comoros',
            self::CPV => 'Cape Verde',
            self::CRI => 'Costa Rica',
            self::CUB => 'Cuba',
            self::CUW => 'Curaçao',
            self::CXR => 'Christmas Island',
            self::CYM => 'Cayman Islands',
            self::CYP => 'Cyprus',
            self::CZE => 'Czech Republic',
            self::DEU => 'Germany',
            self::DJI => 'Djibouti',
            self::DMA => 'Dominica',
            self::DNK => 'Denmark',
            self::DOM => 'Dominican Republic',
            self::DZA => 'Algeria',
            self::ECU => 'Ecuador',
            self::EGY => 'Egypt',
            self::ERI => 'Eritrea',
            self::ESH => 'Western Sahara',
            self::ESP => 'Spain',
            self::EST => 'Estonia',
            self::ETH => 'Ethiopia',
            self::FIN => 'Finland',
            self::FJI => 'Fiji',
            self::FLK => 'Falkland Islands (Malvinas)',
            self::FRA => 'France',
            self::FRO => 'Faroe Islands',
            self::FSM => 'Micronesia, Federated States of',
            self::GAB => 'Gabon',
            self::GBR => 'United Kingdom',
            self::GEO => 'Georgia',
            self::GGY => 'Guernsey',
            self::GHA => 'Ghana',
            self::GIB => 'Gibraltar',
            self::GIN => 'Guinea',
            self::GLP => 'Guadeloupe',
            self::GMB => 'Gambia',
            self::GNB => 'Guinea-Bissau',
            self::GNQ => 'Equatorial Guinea',
            self::GRC => 'Greece',
            self::GRD => 'Grenada',
            self::GRL => 'Greenland',
            self::GTM => 'Guatemala',
            self::GUF => 'French Guiana',
            self::GUM => 'Guam',
            self::GUY => 'Guyana',
            self::HKG => 'Hong Kong',
            self::HMD => 'Heard Island and McDonald Islands',
            self::HND => 'Honduras',
            self::HRV => 'Croatia',
            self::HTI => 'Haiti',
            self::HUN => 'Hungary',
            self::IDN => 'Indonesia',
            self::IMN => 'Isle of Man',
            self::IND => 'India',
            self::IOT => 'British Indian Ocean Territory',
            self::IRL => 'Ireland',
            self::IRN => 'Iran, Islamic Republic of',
            self::IRQ => 'Iraq',
            self::ISL => 'Iceland',
            self::ISR => 'Israel',
            self::ITA => 'Italy',
            self::JAM => 'Jamaica',
            self::JEY => 'Jersey',
            self::JOR => 'Jordan',
            self::JPN => 'Japan',
            self::KAZ => 'Kazakhstan',
            self::KEN => 'Kenya',
            self::KGZ => 'Kyrgyzstan',
            self::KHM => 'Cambodia',
            self::KIR => 'Kiribati',
            self::KNA => 'Saint Kitts and Nevis',
            self::KOR => 'Korea, Republic of',
            self::KWT => 'Kuwait',
            self::LAO => 'Lao People s Democratic Republic',
            self::LBN => 'Lebanon',
            self::LBR => 'Liberia',
            self::LBY => 'Libyan Arab Jamahiriya',
            self::LCA => 'Saint Lucia',
            self::LIE => 'Liechtenstein',
            self::LKA => 'Sri Lanka',
            self::LSO => 'Lesotho',
            self::LTU => 'Lithuania',
            self::LUX => 'Luxembourg',
            self::LVA => 'Latvia',
            self::MAC => 'Macao',
            self::MAF => 'Saint Martin (French part)',
            self::MAR => 'Morocco',
            self::MCO => 'Monaco',
            self::MDA => 'Moldova, Republic of',
            self::MDG => 'Madagascar',
            self::MDV => 'Maldives',
            self::MEX => 'Mexico',
            self::MHL => 'Marshall Islands',
            self::MKD => 'Macedonia, the former Yugoslav Republic of',
            self::MLI => 'Mali',
            self::MLT => 'Malta',
            self::MMR => 'Myanmar',
            self::MNE => 'Montenegro',
            self::MNG => 'Mongolia',
            self::MNP => 'Northern Mariana Islands',
            self::MOZ => 'Mozambique',
            self::MRT => 'Mauritania',
            self::MSR => 'Montserrat',
            self::MTQ => 'Martinique',
            self::MUS => 'Mauritius',
            self::MWI => 'Malawi',
            self::MYS => 'Malaysia',
            self::MYT => 'Mayotte',
            self::NAM => 'Namibia',
            self::NCL => 'New Caledonia',
            self::NER => 'Niger',
            self::NFK => 'Norfolk Island',
            self::NGA => 'Nigeria',
            self::NIC => 'Nicaragua',
            self::NIU => 'Niue',
            self::NLD => 'Netherlands',
            self::NOR => 'Norway',
            self::NPL => 'Nepal',
            self::NRU => 'Nauru',
            self::NZL => 'New Zealand',
            self::OMN => 'Oman',
            self::PAK => 'Pakistan',
            self::PAN => 'Panama',
            self::PCN => 'Pitcairn',
            self::PER => 'Peru',
            self::PHL => 'Philippines',
            self::PLW => 'Palau',
            self::PNG => 'Papua New Guinea',
            self::POL => 'Poland',
            self::PRI => 'Puerto Rico',
            self::PRK => 'Korea, Democratic People s Republic of',
            self::PRT => 'Portugal',
            self::PRY => 'Paraguay',
            self::PSE => 'Palestinian Territory, Occupied',
            self::PYF => 'French Polynesia',
            self::QAT => 'Qatar',
            self::REU => 'Reunion',
            self::ROU => 'Romania',
            self::RUS => 'Russian Federation',
            self::RWA => 'Rwanda',
            self::SAU => 'Saudi Arabia',
            self::SDN => 'Sudan',
            self::SEN => 'Senegal',
            self::SGP => 'Singapore',
            self::SGS => 'South Georgia and the South Sandwich Islands',
            self::SHN => 'Saint Helena, Ascension and Tristan da Cunha',
            self::SJM => 'Svalbard and Jan Mayen',
            self::SLB => 'Solomon Islands',
            self::SLE => 'Sierra Leone',
            self::SLV => 'El Salvador',
            self::SMR => 'San Marino',
            self::SOM => 'Somalia',
            self::SPM => 'Saint Pierre and Miquelon',
            self::SRB => 'Serbia',
            self::STP => 'Sao Tome and Principe',
            self::SUR => 'Suriname',
            self::SVK => 'Slovakia',
            self::SVN => 'Slovenia',
            self::SWE => 'Sweden',
            self::SWZ => 'Swaziland',
            self::SXM => 'Sint Maarten (Dutch part)',
            self::SYC => 'Seychelles',
            self::SYR => 'Syrian Arab Republic',
            self::TCA => 'Turks and Caicos Islands',
            self::TCD => 'Chad',
            self::TGO => 'Togo',
            self::THA => 'Thailand',
            self::TJK => 'Tajikistan',
            self::TKL => 'Tokelau',
            self::TKM => 'Turkmenistan',
            self::TLS => 'Timor-Leste',
            self::TON => 'Tonga',
            self::TTO => 'Trinidad and Tobago',
            self::TUN => 'Tunisia',
            self::TUR => 'Turkey',
            self::TUV => 'Tuvalu',
            self::TWN => 'Taiwan, Province of China',
            self::TZA => 'Tanzania, United Republic of',
            self::UGA => 'Uganda',
            self::UKR => 'Ukraine',
            self::UMI => 'United States Minor Outlying Islands',
            self::URY => 'Uruguay',
            self::USA => 'United States',
            self::UZB => 'Uzbekistan',
            self::VAT => 'Holy See (Vatican City State)',
            self::VCT => 'Saint Vincent and the Grenadines',
            self::VEN => 'Venezuela, Bolivarian Republic of',
            self::VGB => 'Virgin Islands, British',
            self::VIR => 'Virgin Islands, U.S.',
            self::VNM => 'Viet Nam',
            self::VUT => 'Vanuatu',
            self::WLF => 'Wallis and Futuna',
            self::WSM => 'Samoa',
            self::YEM => 'Yemen',
            self::ZAF => 'South Africa',
            self::ZMB => 'Zambia',
            self::ZWE => 'Zimbabwe',
            ];
    }
      
}