<?php
    
namespace Prehmis\HL7Bundle\Tables\v25;

use Elao\Enum\ChoiceEnumTrait;
use Elao\Enum\ReadableEnum;

/**
 * Description of T0487
 * Specimen Type
 * HL7 version 2.5
 *
 */
final class T0487 extends ReadableEnum
{
    use ChoiceEnumTrait;

    const ABS = 'ABS';
    const ACNE = 'ACNE';
    const ACNFLD = 'ACNFLD';
    const AIRS = 'AIRS';
    const ALL = 'ALL';
    const AMP = 'AMP';
    const ANGI = 'ANGI';
    const ARTC = 'ARTC';
    const ASERU = 'ASERU';
    const ASP = 'ASP';
    const ATTE = 'ATTE';
    const AUTOC = 'AUTOC';
    const AUTP = 'AUTP';
    const BBL = 'BBL';
    const BCYST = 'BCYST';
    const BITE = 'BITE';
    const BLEB = 'BLEB';
    const BLIST = 'BLIST';
    const BOIL = 'BOIL';
    const BONE = 'BONE';
    const BOWL = 'BOWL';
    const BPU = 'BPU';
    const BRN = 'BRN';
    const BRSH = 'BRSH';
    const BRTH = 'BRTH';
    const BRUS = 'BRUS';
    const BUB = 'BUB';
    const BULLA = 'BULLA';
    const BX = 'BX';
    const CALC = 'CALC';
    const CARBU = 'CARBU';
    const CAT = 'CAT';
    const CBITE = 'CBITE';
    const CLIPP = 'CLIPP';
    const CNJT = 'CNJT';
    const COL = 'COL';
    const CONE = 'CONE';
    const CSCR = 'CSCR';
    const CSERU = 'CSERU';
    const CSITE = 'CSITE';
    const CSMY = 'CSMY';
    const CST = 'CST';
    const CSVR = 'CSVR';
    const CTP = 'CTP';
    const CVPS = 'CVPS';
    const CVPT = 'CVPT';
    const CYN = 'CYN';
    const CYST = 'CYST';
    const DBITE = 'DBITE';
    const DCS = 'DCS';
    const DEC = 'DEC';
    const DEION = 'DEION';
    const DIA = 'DIA';
    const DISCHG = 'DISCHG';
    const DIV = 'DIV';
    const DRN = 'DRN';
    const DRNG = 'DRNG';
    const DRNGP = 'DRNGP';
    const EARW = 'EARW';
    const EBRUSH = 'EBRUSH';
    const EEYE = 'EEYE';
    const EFF = 'EFF';
    const EFFUS = 'EFFUS';
    const EFOD = 'EFOD';
    const EISO = 'EISO';
    const ELT = 'ELT';
    const ENVIR = 'ENVIR';
    const EOTH = 'EOTH';
    const ESOI = 'ESOI';
    const ESOS = 'ESOS';
    const ETA = 'ETA';
    const ETTP = 'ETTP';
    const ETTUB = 'ETTUB';
    const EWHI = 'EWHI';
    const EXG = 'EXG';
    const EXS = 'EXS';
    const EXUDTE = 'EXUDTE';
    const FAW = 'FAW';
    const FBLOOD = 'FBLOOD';
    const FGA = 'FGA';
    const FIST = 'FIST';
    const FLD = 'FLD';
    const FLT = 'FLT';
    const FLU = 'FLU';
    const FLUID = 'FLUID';
    const FOLEY = 'FOLEY';
    const FRS = 'FRS';
    const FSCLP = 'FSCLP';
    const FUR = 'FUR';
    const GAS = 'GAS';
    const GASA = 'GASA';
    const GASAN = 'GASAN';
    const GASBR = 'GASBR';
    const GASD = 'GASD';
    const GAST = 'GAST';
    const GENV = 'GENV';
    const GRAFT = 'GRAFT';
    const GRANU = 'GRANU';
    const GROSH = 'GROSH';
    const GSOL = 'GSOL';
    const GSPEC = 'GSPEC';
    const GT = 'GT';
    const GTUBE = 'GTUBE';
    const HBITE = 'HBITE';
    const HBLUD = 'HBLUD';
    const HEMAQ = 'HEMAQ';
    const HEMO = 'HEMO';
    const HERNI = 'HERNI';
    const HEV = 'HEV';
    const HIC = 'HIC';
    const HYDC = 'HYDC';
    const IBITE = 'IBITE';
    const ICYST = 'ICYST';
    const IDC = 'IDC';
    const IHG = 'IHG';
    const ILEO = 'ILEO';
    const ILLEG = 'ILLEG';
    const IMP = 'IMP';
    const INCI = 'INCI';
    const INFIL = 'INFIL';
    const INS = 'INS';
    const INTRD = 'INTRD';
    const IT = 'IT';
    const IUD = 'IUD';
    const IVCAT = 'IVCAT';
    const IVFLD = 'IVFLD';
    const IVTIP = 'IVTIP';
    const JEJU = 'JEJU';
    const JNTFLD = 'JNTFLD';
    const JP = 'JP';
    const KELOI = 'KELOI';
    const KIDFLD = 'KIDFLD';
    const LAVG = 'LAVG';
    const LAVGG = 'LAVGG';
    const LAVGP = 'LAVGP';
    const LAVPG = 'LAVPG';
    const LENS1 = 'LENS1';
    const LENS2 = 'LENS2';
    const LESN = 'LESN';
    const LIQ = 'LIQ';
    const LIQO = 'LIQO';
    const LSAC = 'LSAC';
    const MAHUR = 'MAHUR';
    const MASS = 'MASS';
    const MBLD = 'MBLD';
    const MUCOS = 'MUCOS';
    const MUCUS = 'MUCUS';
    const NASDR = 'NASDR';
    const NEDL = 'NEDL';
    const NEPH = 'NEPH';
    const NGASP = 'NGASP';
    const NGAST = 'NGAST';
    const NGS = 'NGS';
    const NODUL = 'NODUL';
    const NSECR = 'NSECR';
    const ORH = 'ORH';
    const ORL = 'ORL';
    const OTH = 'OTH';
    const PACEM = 'PACEM';
    const PCFL = 'PCFL';
    const PDSIT = 'PDSIT';
    const PDTS = 'PDTS';
    const PELVA = 'PELVA';
    const PENIL = 'PENIL';
    const PERIA = 'PERIA';
    const PILOC = 'PILOC';
    const PINS = 'PINS';
    const PIS = 'PIS';
    const PLAN = 'PLAN';
    const PLAS = 'PLAS';
    const PLB = 'PLB';
    const PLEVS = 'PLEVS';
    const PND = 'PND';
    const POL = 'POL';
    const POPGS = 'POPGS';
    const POPLG = 'POPLG';
    const POPLV = 'POPLV';
    const PORTA = 'PORTA';
    const PPP = 'PPP';
    const PROST = 'PROST';
    const PRP = 'PRP';
    const PSC = 'PSC';
    const PUNCT = 'PUNCT';
    const PUSFR = 'PUSFR';
    const PUST = 'PUST';
    const QC3 = 'QC3';
    const RANDU = 'RANDU';
    const RBITE = 'RBITE';
    const RECT = 'RECT';
    const RECTA = 'RECTA';
    const RENALC = 'RENALC';
    const RENC = 'RENC';
    const RES = 'RES';
    const SAL = 'SAL';
    const SCAR = 'SCAR';
    const SCLV = 'SCLV';
    const SCROA = 'SCROA';
    const SECRE = 'SECRE';
    const SER = 'SER';
    const SHU = 'SHU';
    const SHUNF = 'SHUNF';
    const SHUNT = 'SHUNT';
    const SITE = 'SITE';
    const SKBP = 'SKBP';
    const SKN = 'SKN';
    const SMM = 'SMM';
    const SNV = 'SNV';
    const SPRM = 'SPRM';
    const SPRP = 'SPRP';
    const SPRPB = 'SPRPB';
    const SPS = 'SPS';
    const SPT = 'SPT';
    const SPTC = 'SPTC';
    const SPTT = 'SPTT';
    const SPUT1 = 'SPUT1';
    const SPUTIN = 'SPUTIN';
    const SPUTSP = 'SPUTSP';
    const STER = 'STER';
    const STL = 'STL';
    const STONE = 'STONE';
    const SUBMA = 'SUBMA';
    const SUBMX = 'SUBMX';
    const SUMP = 'SUMP';
    const SUP = 'SUP';
    const SUTUR = 'SUTUR';
    const SWGZ = 'SWGZ';
    const TASP = 'TASP';
    const TISS = 'TISS';
    const TISU = 'TISU';
    const TLC = 'TLC';
    const TRAC = 'TRAC';
    const TRANS = 'TRANS';
    const TSERU = 'TSERU';
    const TSTES = 'TSTES';
    const TTRA = 'TTRA';
    const TUBES = 'TUBES';
    const TUMOR = 'TUMOR';
    const TZANC = 'TZANC';
    const UDENT = 'UDENT';
    const UR = 'UR';
    const URC = 'URC';
    const URINB = 'URINB';
    const URINC = 'URINC';
    const URINM = 'URINM';
    const URINN = 'URINN';
    const URINP = 'URINP';
    const URT = 'URT';
    const USCOP = 'USCOP';
    const USPEC = 'USPEC';
    const VASTIP = 'VASTIP';
    const VENT = 'VENT';
    const VITF = 'VITF';
    const WASH = 'WASH';
    const WASI = 'WASI';
    const WAT = 'WAT';
    const WB = 'WB';
    const WEN = 'WEN';
    const WICK = 'WICK';
    const WND = 'WND';
    const WNDA = 'WNDA';
    const WNDD = 'WNDD';
    const WNDE = 'WNDE';
    const WORM = 'WORM';
    const WRT = 'WRT';
    const WWA = 'WWA';
    const WWO = 'WWO';
    const WWT = 'WWT';
            
    public static function choices(): array
    {
        return [
            self::ABS => 'Abscess',
            self::ACNE => 'Tissue, Acne',
            self::ACNFLD => 'Fluid, Acne',
            self::AIRS => 'Air Sample',
            self::ALL => 'Allograft',
            self::AMP => 'Amputation',
            self::ANGI => 'Catheter Tip, Angio',
            self::ARTC => 'Catheter Tip, Arterial',
            self::ASERU => 'Serum, Acute',
            self::ASP => 'Aspirate',
            self::ATTE => 'Environment, Attest',
            self::AUTOC => 'Environmental, Autoclave Capsule',
            self::AUTP => 'Autopsy',
            self::BBL => 'Blood bag',
            self::BCYST => 'Cyst, Bakers',
            self::BITE => 'Bite',
            self::BLEB => 'Bleb',
            self::BLIST => 'Blister',
            self::BOIL => 'Boil',
            self::BONE => 'Bone',
            self::BOWL => 'Bowel contents',
            self::BPU => 'Blood product unit',
            self::BRN => 'Burn',
            self::BRSH => 'Brush',
            self::BRTH => 'Breath (use EXHLD)',
            self::BRUS => 'Brushing',
            self::BUB => 'Bubo',
            self::BULLA => 'Bulla/Bullae',
            self::BX => 'Biopsy',
            self::CALC => 'Calculus (=Stone)',
            self::CARBU => 'Carbuncle',
            self::CAT => 'Catheter',
            self::CBITE => 'Bite, Cat',
            self::CLIPP => 'Clippings',
            self::CNJT => 'Conjunctiva',
            self::COL => 'Colostrum',
            self::CONE => 'Biospy, Cone',
            self::CSCR => 'Scratch, Cat',
            self::CSERU => 'Serum, Convalescent',
            self::CSITE => 'Catheter Insertion Site',
            self::CSMY => 'Fluid, Cystostomy Tube',
            self::CST => 'Fluid, Cyst',
            self::CSVR => 'Blood, Cell Saver',
            self::CTP => 'Catheter tip',
            self::CVPS => 'Site, CVP',
            self::CVPT => 'Catheter Tip, CVP',
            self::CYN => 'Nodule, Cystic',
            self::CYST => 'Cyst',
            self::DBITE => 'Bite, Dog',
            self::DCS => 'Sputum, Deep Cough',
            self::DEC => 'Ulcer, Decubitus',
            self::DEION => 'Environmental, Water (Deionized)',
            self::DIA => 'Dialysate',
            self::DISCHG => 'Discharge',
            self::DIV => 'Diverticulum',
            self::DRN => 'Drain',
            self::DRNG => 'Drainage, Tube',
            self::DRNGP => 'Drainage, Penrose',
            self::EARW => 'Ear wax (cerumen)',
            self::EBRUSH => 'Brush, Esophageal',
            self::EEYE => 'Environmental, Eye Wash',
            self::EFF => 'Environmental, Effluent',
            self::EFFUS => 'Effusion',
            self::EFOD => 'Environmental, Food',
            self::EISO => 'Environmental, Isolette',
            self::ELT => 'Electrode',
            self::ENVIR => 'Environmental, Unidentified Substance',
            self::EOTH => 'Environmental, Other Substance',
            self::ESOI => 'Environmental, Soil',
            self::ESOS => 'Environmental, Solution (Sterile)',
            self::ETA => 'Aspirate, Endotrach',
            self::ETTP => 'Catheter Tip, Endotracheal',
            self::ETTUB => 'Tube, Endotracheal',
            self::EWHI => 'Environmental, Whirlpool',
            self::EXG => 'Gas, exhaled (=breath)',
            self::EXS => 'Shunt, External',
            self::EXUDTE => 'Exudate',
            self::FAW => 'Environmental, Water (Well)',
            self::FBLOOD => 'Blood, Fetal',
            self::FGA => 'Fluid, Abdomen',
            self::FIST => 'Fistula',
            self::FLD => 'Fluid, Other',
            self::FLT => 'Filter',
            self::FLU => 'Fluid, Body unsp',
            self::FLUID => 'Fluid',
            self::FOLEY => 'Catheter Tip, Foley',
            self::FRS => 'Fluid, Respiratory',
            self::FSCLP => 'Scalp, Fetal',
            self::FUR => 'Furuncle',
            self::GAS => 'Gas',
            self::GASA => 'Aspirate, Gastric',
            self::GASAN => 'Antrum, Gastric',
            self::GASBR => 'Brushing, Gastric',
            self::GASD => 'Drainage, Gastric',
            self::GAST => 'Fluid/contents, Gastric',
            self::GENV => 'Genital vaginal',
            self::GRAFT => 'Graft',
            self::GRANU => 'Granuloma',
            self::GROSH => 'Catheter, Groshong',
            self::GSOL => 'Solution, Gastrostomy',
            self::GSPEC => 'Biopsy, Gastric',
            self::GT => 'Tube, Gastric',
            self::GTUBE => 'Drainage Tube, Drainage (Gastrostomy)',
            self::HBITE => 'Bite, Human',
            self::HBLUD => 'Blood, Autopsy',
            self::HEMAQ => 'Catheter Tip, Hemaquit',
            self::HEMO => 'Catheter Tip, Hemovac',
            self::HERNI => 'Tissue, Herniated',
            self::HEV => 'Drain, Hemovac',
            self::HIC => 'Catheter, Hickman',
            self::HYDC => 'Fluid, Hydrocele',
            self::IBITE => 'Bite, Insect',
            self::ICYST => 'Cyst, Inclusion',
            self::IDC => 'Catheter Tip, Indwelling',
            self::IHG => 'Gas, Inhaled',
            self::ILEO => 'Drainage, Ileostomy',
            self::ILLEG => 'Source of Specimen Is Illegible',
            self::IMP => 'Implant',
            self::INCI => 'Site, Incision/Surgical',
            self::INFIL => 'Infiltrate',
            self::INS => 'Insect',
            self::INTRD => 'Catheter Tip, Introducer',
            self::IT => 'Intubation tube',
            self::IUD => 'Intrauterine Device',
            self::IVCAT => 'Catheter Tip, IV',
            self::IVFLD => 'Fluid, IV',
            self::IVTIP => 'Tubing Tip, IV',
            self::JEJU => 'Drainage, Jejunal',
            self::JNTFLD => 'Fluid, Joint',
            self::JP => 'Drainage, Jackson Pratt',
            self::KELOI => 'Lavage',
            self::KIDFLD => 'Fluid, Kidney',
            self::LAVG => 'Lavage, Bronhial',
            self::LAVGG => 'Lavage, Gastric',
            self::LAVGP => 'Lavage, Peritoneal',
            self::LAVPG => 'Lavage, Pre-Bronch',
            self::LENS1 => 'Contact Lens',
            self::LENS2 => 'Contact Lens Case',
            self::LESN => 'Lesion',
            self::LIQ => 'Liquid, Unspecified',
            self::LIQO => 'Liquid, Other',
            self::LSAC => 'Fluid, Lumbar Sac',
            self::MAHUR => 'Catheter Tip, Makurkour',
            self::MASS => 'Mass',
            self::MBLD => 'Blood, Menstrual',
            self::MUCOS => 'Mucosa',
            self::MUCUS => 'Mucus',
            self::NASDR => 'Drainage, Nasal',
            self::NEDL => 'Needle',
            self::NEPH => 'Site, Nephrostomy',
            self::NGASP => 'Aspirate, Nasogastric',
            self::NGAST => 'Drainage, Nasogastric',
            self::NGS => 'Site, Naso/Gastric',
            self::NODUL => 'Nodule(s)',
            self::NSECR => 'Secretion, Nasal',
            self::ORH => 'Other',
            self::ORL => 'Lesion, Oral',
            self::OTH => 'Source, Other',
            self::PACEM => 'Pacemaker',
            self::PCFL => 'Fluid, Pericardial',
            self::PDSIT => 'Site, Peritoneal Dialysis',
            self::PDTS => 'Site, Peritoneal Dialysis Tunnel',
            self::PELVA => 'Abscess, Pelvic',
            self::PENIL => 'Lesion, Penile',
            self::PERIA => 'Abscess, Perianal',
            self::PILOC => 'Cyst, Pilonidal',
            self::PINS => 'Site, Pin',
            self::PIS => 'Site, Pacemaker Insetion',
            self::PLAN => 'Plant Material',
            self::PLAS => 'Plasma',
            self::PLB => 'Plasma bag',
            self::PLEVS => 'Serum, Peak Level',
            self::PND => 'Drainage, Penile',
            self::POL => 'Polyps',
            self::POPGS => 'Graft Site, Popliteal',
            self::POPLG => 'Graft, Popliteal',
            self::POPLV => 'Site, Popliteal Vein',
            self::PORTA => 'Catheter, Porta',
            self::PPP => 'Plasma, Platelet poor',
            self::PROST => 'Prosthetic Device',
            self::PRP => 'Plasma, Platelet rich',
            self::PSC => 'Pseudocyst',
            self::PUNCT => 'Wound, Puncture',
            self::PUSFR => 'Pustule',
            self::PUST => 'Pus',
            self::QC3 => 'Quality Control',
            self::RANDU => 'Urine, Random',
            self::RBITE => 'Bite, Reptile',
            self::RECT => 'Drainage, Rectal',
            self::RECTA => 'Abscess, Rectal',
            self::RENALC => 'Cyst, Renal',
            self::RENC => 'Fluid, Renal Cyst',
            self::RES => 'Respiratory',
            self::SAL => 'Saliva',
            self::SCAR => 'Tissue, Keloid (Scar)',
            self::SCLV => 'Catheter Tip, Subclavian',
            self::SCROA => 'Abscess, Scrotal',
            self::SECRE => 'Secretion(s)',
            self::SER => 'Serum',
            self::SHU => 'Site, Shunt',
            self::SHUNF => 'Fluid, Shunt',
            self::SHUNT => 'Shunt',
            self::SITE => 'Site',
            self::SKBP => 'Biopsy, Skin',
            self::SKN => 'Skin',
            self::SMM => 'Mass, Sub-Mandibular',
            self::SNV => 'Fluid, synovial (Joint fluid)',
            self::SPRM => 'Spermatozoa',
            self::SPRP => 'Catheter Tip, Suprapubic',
            self::SPRPB => 'Cathether Tip, Suprapubic',
            self::SPS => 'Environmental, Spore Strip',
            self::SPT => 'Sputum',
            self::SPTC => 'Sputum - coughed',
            self::SPTT => 'Sputum - tracheal aspirate',
            self::SPUT1 => 'Sputum, Simulated',
            self::SPUTIN => 'Sputum, Inducted',
            self::SPUTSP => 'Sputum, Spontaneous',
            self::STER => 'Environmental, Sterrad',
            self::STL => 'Stool = Fecal',
            self::STONE => 'Stone, Kidney',
            self::SUBMA => 'Abscess, Submandibular',
            self::SUBMX => 'Abscess, Submaxillary',
            self::SUMP => 'Drainage, Sump',
            self::SUP => 'Suprapubic Tap',
            self::SUTUR => 'Suture',
            self::SWGZ => 'Catheter Tip, Swan Gantz',
            self::TASP => 'Aspirate, Tracheal',
            self::TISS => 'Tissue',
            self::TISU => 'Tissue ulcer',
            self::TLC => 'Cathether Tip, Triple Lumen',
            self::TRAC => 'Site, Tracheostomy',
            self::TRANS => 'Transudate',
            self::TSERU => 'Serum, Trough',
            self::TSTES => 'Abscess, Testicular',
            self::TTRA => 'Aspirate, Transtracheal',
            self::TUBES => 'Tubes',
            self::TUMOR => 'Tumor',
            self::TZANC => 'Smear, Tzanck',
            self::UDENT => 'Source, Unidentified',
            self::UR => 'Urine',
            self::URC => 'Urine clean catch',
            self::URINB => 'Urine, Bladder Washings',
            self::URINC => 'Urine, Catheterized',
            self::URINM => 'Urine, Midstream',
            self::URINN => 'Urine, Nephrostomy',
            self::URINP => 'Urine, Pedibag',
            self::URT => 'Urine catheter',
            self::USCOP => 'Urine, Cystoscopy',
            self::USPEC => 'Source, Unspecified',
            self::VASTIP => 'Catheter Tip, Vas',
            self::VENT => 'Catheter Tip, Ventricular',
            self::VITF => 'Vitreous Fluid',
            self::WASH => 'Wash',
            self::WASI => 'Washing, e.g. bronchial washing',
            self::WAT => 'Water',
            self::WB => 'Blood, Whole',
            self::WEN => 'Wen',
            self::WICK => 'Wick',
            self::WND => 'Wound',
            self::WNDA => 'Wound abscess',
            self::WNDD => 'Wound drainage',
            self::WNDE => 'Wound exudate',
            self::WORM => 'Worm',
            self::WRT => 'Wart',
            self::WWA => 'Environmental, Water',
            self::WWO => 'Environmental, Water (Ocean)',
            self::WWT => 'Environmental, Water (Tap)',
            ];
    }
      
}